extern crate cbindgen;

fn main() {
  let crate_path = env!("CARGO_MANIFEST_DIR");

  let config = cbindgen::Config {
    language: cbindgen::Language::C,
    include_guard: Some("TINYALLOC_H".to_string()),
    package_version: true,
    autogen_warning: Some(
      "/* This file is automatically generated. Do not edit. */".to_string(),
    ),
    braces: cbindgen::Braces::SameLine,
    line_endings: cbindgen::LineEndingStyle::LF,
    line_length: 100,
    tab_width: 2,
    usize_is_size_t: true,
    cpp_compat: true,
    function: cbindgen::FunctionConfig {
      ..Default::default()
    },
    enumeration: cbindgen::EnumConfig {
      ..Default::default()
    },
    structure: cbindgen::StructConfig {
      ..Default::default()
    },
    export: cbindgen::ExportConfig {
      ..Default::default()
    },
    ..Default::default()
  };

  cbindgen::Builder::new()
    .with_config(config)
    .with_crate(crate_path)
    .generate()
    .unwrap()
    .write_to_file("tinyalloc.h");
}
