[package]
name = "tinyalloc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "dylib", "staticlib"]

[dependencies]
tinyalloc-sys = { workspace = true }
tinyalloc-alloc = { workspace = true }

[workspace]
resolver = "3"
members = [
  "crates/tinyalloc-alloc",
  "crates/tinyalloc-bitmap",
  "crates/tinyalloc-sys",
]

[workspace.dependencies]
enumset = "1.1.10"
getset = "0.1.6"
libc = "0.2.175"
page_size = "0.6.0"
windows-sys = "0.60.2"

tinyalloc-sys = { path = "crates/tinyalloc-sys" }
tinyalloc-alloc = { path = "crates/tinyalloc-alloc" }
tinyalloc-bitmap = { path = "crates/tinyalloc-bitmap" }
