#ifndef TINYALLOC_H
#define TINYALLOC_H

/*
 * This file is autogenerated by cbindgen.
 * Do not modify this file directly.
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

void *malloc(size_t size);

void *calloc(size_t nmemb, size_t size);

void free(void *ptr);

void *aligned_alloc(size_t alignment, size_t size);

void *realloc(void *ptr, size_t size);

#endif  /* TINYALLOC_H */
