/* Package version: 0.1.0 */

#ifndef TINYALLOC_H
#define TINYALLOC_H

/* This file is automatically generated. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* TINYALLOC_H */
