[package]
name = "tinyalloc-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
getset = { workspace = true }
libc = { workspace = true }
enumset = { workspace = true }
windows-sys = { workspace = true, features = ["Win32_System_Memory"] }