[package]
name = "tinyalloc-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
tinyalloc-core = { workspace = true }
libc = { workspace = true }
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Memory",
] }
